
name: "release godon-metrics-exporter image"

on:
  push:
    tags:
      - 'godon-metrics-exporter-*'

jobs:
  build-and-release-image:
    uses: ./.github/workflows/release-image.yml
    secrets: inherit